/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as OpensearchDotxmlRouteImport } from './routes/opensearch[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiSuggestRouteImport } from './routes/api/suggest'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedSearchIndexRouteImport } from './routes/_authed/search/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedSettingsUsersRouteImport } from './routes/_authed/settings/users'
import { Route as AuthedSettingsSearchRouteImport } from './routes/_authed/settings/search'
import { Route as AuthedSettingsPrivacyRouteImport } from './routes/_authed/settings/privacy'
import { Route as AuthedSettingsGeneralRouteImport } from './routes/_authed/settings/general'
import { Route as AuthedSettingsAppearanceRouteImport } from './routes/_authed/settings/appearance'
import { Route as AuthedSettingsApiRouteImport } from './routes/_authed/settings/api'
import { Route as AuthedSettingsAboutRouteImport } from './routes/_authed/settings/about'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const OpensearchDotxmlRoute = OpensearchDotxmlRouteImport.update({
  id: '/opensearch.xml',
  path: '/opensearch.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiSuggestRoute = ApiSuggestRouteImport.update({
  id: '/api/suggest',
  path: '/api/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSearchIndexRoute = AuthedSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsUsersRoute = AuthedSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsSearchRoute = AuthedSettingsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsPrivacyRoute = AuthedSettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsGeneralRoute = AuthedSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsAppearanceRoute =
  AuthedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsApiRoute = AuthedSettingsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsAboutRoute = AuthedSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthedSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/opensearch.xml': typeof OpensearchDotxmlRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/settings/about': typeof AuthedSettingsAboutRoute
  '/settings/api': typeof AuthedSettingsApiRoute
  '/settings/appearance': typeof AuthedSettingsAppearanceRoute
  '/settings/general': typeof AuthedSettingsGeneralRoute
  '/settings/privacy': typeof AuthedSettingsPrivacyRoute
  '/settings/search': typeof AuthedSettingsSearchRoute
  '/settings/users': typeof AuthedSettingsUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/search/': typeof AuthedSearchIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/opensearch.xml': typeof OpensearchDotxmlRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/': typeof AuthedIndexRoute
  '/settings/about': typeof AuthedSettingsAboutRoute
  '/settings/api': typeof AuthedSettingsApiRoute
  '/settings/appearance': typeof AuthedSettingsAppearanceRoute
  '/settings/general': typeof AuthedSettingsGeneralRoute
  '/settings/privacy': typeof AuthedSettingsPrivacyRoute
  '/settings/search': typeof AuthedSettingsSearchRoute
  '/settings/users': typeof AuthedSettingsUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/search': typeof AuthedSearchIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/opensearch.xml': typeof OpensearchDotxmlRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/search': typeof ApiSearchRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/settings/about': typeof AuthedSettingsAboutRoute
  '/_authed/settings/api': typeof AuthedSettingsApiRoute
  '/_authed/settings/appearance': typeof AuthedSettingsAppearanceRoute
  '/_authed/settings/general': typeof AuthedSettingsGeneralRoute
  '/_authed/settings/privacy': typeof AuthedSettingsPrivacyRoute
  '/_authed/settings/search': typeof AuthedSettingsSearchRoute
  '/_authed/settings/users': typeof AuthedSettingsUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/search/': typeof AuthedSearchIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/opensearch.xml'
    | '/setup'
    | '/signup'
    | '/settings'
    | '/api/health'
    | '/api/search'
    | '/api/suggest'
    | '/settings/about'
    | '/settings/api'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/privacy'
    | '/settings/search'
    | '/settings/users'
    | '/api/auth/$'
    | '/search/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/opensearch.xml'
    | '/setup'
    | '/signup'
    | '/api/health'
    | '/api/search'
    | '/api/suggest'
    | '/'
    | '/settings/about'
    | '/settings/api'
    | '/settings/appearance'
    | '/settings/general'
    | '/settings/privacy'
    | '/settings/search'
    | '/settings/users'
    | '/api/auth/$'
    | '/search'
    | '/settings'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/opensearch.xml'
    | '/setup'
    | '/signup'
    | '/_authed/settings'
    | '/api/health'
    | '/api/search'
    | '/api/suggest'
    | '/_authed/'
    | '/_authed/settings/about'
    | '/_authed/settings/api'
    | '/_authed/settings/appearance'
    | '/_authed/settings/general'
    | '/_authed/settings/privacy'
    | '/_authed/settings/search'
    | '/_authed/settings/users'
    | '/api/auth/$'
    | '/_authed/search/'
    | '/_authed/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OpensearchDotxmlRoute: typeof OpensearchDotxmlRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiSuggestRoute: typeof ApiSuggestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opensearch.xml': {
      id: '/opensearch.xml'
      path: '/opensearch.xml'
      fullPath: '/opensearch.xml'
      preLoaderRoute: typeof OpensearchDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/suggest': {
      id: '/api/suggest'
      path: '/api/suggest'
      fullPath: '/api/suggest'
      preLoaderRoute: typeof ApiSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/search/': {
      id: '/_authed/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof AuthedSearchIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings/users': {
      id: '/_authed/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthedSettingsUsersRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/search': {
      id: '/_authed/settings/search'
      path: '/search'
      fullPath: '/settings/search'
      preLoaderRoute: typeof AuthedSettingsSearchRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/privacy': {
      id: '/_authed/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AuthedSettingsPrivacyRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/general': {
      id: '/_authed/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthedSettingsGeneralRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/appearance': {
      id: '/_authed/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthedSettingsAppearanceRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/api': {
      id: '/_authed/settings/api'
      path: '/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof AuthedSettingsApiRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/about': {
      id: '/_authed/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AuthedSettingsAboutRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
  }
}

interface AuthedSettingsRouteChildren {
  AuthedSettingsAboutRoute: typeof AuthedSettingsAboutRoute
  AuthedSettingsApiRoute: typeof AuthedSettingsApiRoute
  AuthedSettingsAppearanceRoute: typeof AuthedSettingsAppearanceRoute
  AuthedSettingsGeneralRoute: typeof AuthedSettingsGeneralRoute
  AuthedSettingsPrivacyRoute: typeof AuthedSettingsPrivacyRoute
  AuthedSettingsSearchRoute: typeof AuthedSettingsSearchRoute
  AuthedSettingsUsersRoute: typeof AuthedSettingsUsersRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsAboutRoute: AuthedSettingsAboutRoute,
  AuthedSettingsApiRoute: AuthedSettingsApiRoute,
  AuthedSettingsAppearanceRoute: AuthedSettingsAppearanceRoute,
  AuthedSettingsGeneralRoute: AuthedSettingsGeneralRoute,
  AuthedSettingsPrivacyRoute: AuthedSettingsPrivacyRoute,
  AuthedSettingsSearchRoute: AuthedSettingsSearchRoute,
  AuthedSettingsUsersRoute: AuthedSettingsUsersRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedSearchIndexRoute: typeof AuthedSearchIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedSearchIndexRoute: AuthedSearchIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  OpensearchDotxmlRoute: OpensearchDotxmlRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiSuggestRoute: ApiSuggestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
